version: '3'
services:
    jupyter:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                http_proxy: $http_proxy
                HTTP_PROXY: $HTTP_PROXY
                https_proxy: $https_proxy
                HTTPS_PROXY: $HTTPS_PROXY
        entrypoint: start.sh jupyter lab --LabApp.token=''
        environment:
                http_proxy: $http_proxy
                HTTP_PROXY: $HTTP_PROXY
                https_proxy: $https_proxy
                HTTPS_PROXY: $HTTPS_PROXY
