version: '3'
services:
    devops:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                http_proxy: $http_proxy
                HTTP_PROXY: $HTTP_PROXY
                https_proxy: $https_proxy
                HTTPS_PROXY: $HTTPS_PROXY
        entrypoint: sh
        environment:
                http_proxy: $http_proxy
                HTTP_PROXY: $HTTP_PROXY
                https_proxy: $https_proxy
                HTTPS_PROXY: $HTTPS_PROXY
# vim: sw=4 ts=4 expandtab invlist:

